modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ShinQdan/oyoroi"

# A list of mods
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}"
# The version number of the mod
version="${mod_version}"
 # A display name for the mod
displayName="${mod_name}"
# A URL to query for updates for this mod.
#updateJSONURL="https://change.me.example.invalid/updates.json"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="oyoroi.png" #optional
credits="KlaraAga"
authors="${mod_authors}"

# The description text for the mod
description='''
${mod_description}
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
